### ISSUE TITLE
jpeg quality

### ISSUE THREAD

**Issue by prohtex** [ingve/ql-thumbnail#1]
This is very handy, thank you! Is there any chance of being able to set jpeg quality level for the generated thumb? Thanks!

**Comment by ingve** [comment]
I personally only use this for lossless compression where the generated thumbnails are saved as PNGs, but it does appear that [CGImageDestinationAddImage](https://developer.apple.com/documentation/imageio/1464962-cgimagedestinationaddimage?language=objc) can accept a [kCGImageDestinationLossyCompressionQuality](https://developer.apple.com/documentation/imageio/kcgimagedestinationlossycompressionquality?language=objc) property:

> The desired compression quality to use when writing to an image destination. If present, the value associated with this key must be a CFNumberRef data type in the range 0.0 to 1.0. A value of 1.0 specifies to use lossless compression if destination format supports it. A value of 0.0 implies to use maximum compression.

**Comment by prohtex** [comment]
Thanks ! I'm good with PHP but kind of a C dunce. I'd modify line 46 and recompile ?

CGImageDestinationAddImage(thumbnail_, image_, nullptr);

CGImageDestinationAddImage(thumbnail_, image_, .5);

for example? Is there a way to pass this through the command line? I'm calling your wrapper from a PHP script with exec();

Thanks again!

**Comment by ingve** [comment]
Could you try the changes in #3 and let me know how that works for you?

**Comment by prohtex** [comment]
Thanks so much! I will test this now. My script iterates over a pretty large filesystem with many, many different filetypes so this should be a good test. It makes about 900,000 thumbs and takes about a day. I'll let you know if anything unusual happens!

**Comment by prohtex** [comment]
Seems to be going well so far. FYI for any interested parties, it seems the default quality level for jpeg-2000 (and probably also jpeg) is .5 -- pretty low but fine for a thumbnail, I guess

**Comment by ingve** [comment]
Hopefully Apple will add support for HEIF in macOS; that could potentially be a useful format for compressed thumbnails with a good size-to-quality ratio. 

For now, I have merged the changes in #3, so the optional quality setting is now a permanent feature, thanks for the suggestion!
