### ISSUE TITLE
Icon mode

### ISSUE THREAD

**Issue by cylott** [ingve/ql-thumbnail#5]
Is it possible to use this tool to generate previews in icon mode, similar to "qlmanage -ti"?

**Comment by ingve** [comment]
Hi @cylott!

This is currently not supported in this tool, but it would be easy enough to add (basically, we just need to add `kQLThumbnailOptionIconModeKey` to an options dictionary and set it to true instead of passing the null pointer when calling `QLThumbnailImageCreate()`).

Would it be useful? (Are usable icons returned for most file types?) 
How should the functionality be exposed? A command line flag (`--icon`?) The number of parameters is already very long, and the tool has "thumbnail" in the name, so maybe the icon generation should be in a separate binary?

**Comment by cylott** [comment]
> Would it be useful? (Are usable icons returned for most file types?)

Absolutely - I use qlmanage presently but there are limitation (no explicit file output naming, no jpg generation, etc). I've found almost all files create a useful icon.

> How should the functionality be exposed? A command line flag (`--icon`?) The number of parameters is already very long, and the tool has "thumbnail" in the name, so maybe the icon generation should be in a separate binary?

I'd be very happy with either a binary called "ql-icon" or a "--icon" flag. If it was a flag, I'd probably just write a short wrapper script.

Thanks so much for getting back to me and for this very useful tool!

**Comment by cylott** [comment]
Also, one thing I've noticed in my testing is that qlmanage produces completely different icons depending on how the size of the icon is defined.

For example:
`qlmanage -ti -f 4 -o . Redacted-Mueller-Report.pdf`
![b_Redacted-Mueller-Report pdf](https://user-images.githubusercontent.com/42451226/59557748-950c7a00-8f96-11e9-85b4-bf4ea83aa3ce.png)

`qlmanage -ti -s 512 -o . Redacted-Mueller-Report.pdf`
![a_Redacted-Mueller-Report pdf](https://user-images.githubusercontent.com/42451226/59557750-9e95e200-8f96-11e9-8007-3db197a3f752.png)

**Comment by cylott** [comment]
What I would *really* love, would be if there was some way to define the compression level of the resulting png. qlmanage doesn't support this, and so I'm forced to run my png's through imagemagick or pngcrush to get the filesize down.

**Comment by cylott** [comment]
I tried to dive into Xcode to add the suggested changes, but didn't get very far. I'd really love to test this out if there's any way to have the flag added. Thanks for your work on this very helpful tool!

**Comment by ingve** [comment]
I am experimenting/playing with this is a separate repo for now: [ql-icon](https://github.com/ingve/ql-icon).
Very WIP (no documentation yet, the command line interface is slightly different), but feel free to post any feedback there.

**Comment by cylott** [comment]
Thanks so much! This is really wonderful. I'll follow up there.
